sudo: false
language: d
d:
  - dmd
  - gdc
  - ldc

os:
  - linux
  - osx

matrix:
  exclude:
    - d: gdc
      os: osx

install:
  - if [ "$DC" == dmd ]; then
      dub fetch reggae;
      dub run reggae -- --version;
    fi

script:
  - dub build -b debug --compiler=$DC --arch=x86
  - dub build -b debug --compiler=$DC --arch=x86_64
  - if [ "$DC" == dmd ]; then
      dub run reggae -- -b make -d ARCH=x86_64 --no_comp_db;
      make;
    fi
