version: 2

jobs:
  # Simple x86_64 build. It'd be nice to test x86 builds too, but I am too lazy for that
  "x86_64": &build
    working_directory: "x86_64"
    docker:
      - image: dlanguage/dmd:2.077.0
        environment:
          MUSL_VERSION: 1.1.15
          DOCKER_VERSION: "17.03.0-ce"
          MAKEFLAGS: "-j 2"
    steps:
      - checkout
      - run: &install_dependencies
          name: Install dependencies
          command: |
            apt-get update -qq
            apt-get install -y curl file make
      - run: &fetch_reggae
          name: Fetch reggae
          command: |
            dub fetch reggae
            dub run reggae -- --version
      - run:
          name: Build goinsu x86_64
          command: |
            dub run reggae -- -b make -d ARCH=x86_64 --no_comp_db
            make
      - run: &print_info
          name: Check executable
          command: |
            set +o pipefail
            file goinsu
            ldd -v goinsu || true
      - setup_remote_docker
      - run: &install_docker
          name: Install Docker client
          command: |
            set +o pipefail
            curl -fsSL https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz | tar -zx -C /tmp
            mv /tmp/docker/* /usr/bin
      - run: &test
          name: Test
          command: |
            docker build -t test -f .circleci/Dockerfile.test .

  # Build and test x86_64 executable which is statically linked with libc (musl)
  "x86_64.static":
    <<: *build
    working_directory: "x86_64.static"
    steps:
      - checkout
      - run:
          <<: *install_dependencies
      - run:
          <<: *fetch_reggae
      - run:
          name: Build x86_64 musl
          command: |
            cd /tmp
            curl -fsSL http://www.musl-libc.org/releases/musl-$MUSL_VERSION.tar.gz | tar zx
            cd musl-$MUSL_VERSION
            ./configure --disable-shared
            make -s
            echo 'export STATIC_LIBC=/tmp/musl-$MUSL_VERSION/lib/libc.a' >> $BASH_ENV
      - run:
          name: Build static goinsu x86_64
          command: |
            dub run reggae -- -b make -d ARCH=x86_64 -d BUILD_STATIC=true \
              -d STATIC_LIBC=$STATIC_LIBC --no_comp_db
            make
      - run:
          <<: *print_info
      - setup_remote_docker
      - run:
          <<: *install_docker
      - run: &test
          name: Test
          command: |
            sed -i "1s/glibc/musl/" .circleci/Dockerfile.test
            docker build -t test -f .circleci/Dockerfile.test .

  # Same for x86
  "x86.static":
    <<: *build
    working_directory: "x86.static"
    steps:
      - checkout
      - run:
          name: Install dependencies
          # gcc-multilib required
          command: |
            apt-get update -qq
            apt-get install -y curl file make gcc-multilib
      - run:
          <<: *fetch_reggae
      - run:
          name: Build x86 musl
          command: |
            cd /tmp
            curl -fsSL http://www.musl-libc.org/releases/musl-$MUSL_VERSION.tar.gz | tar zx
            cd musl-$MUSL_VERSION
            ./configure --disable-shared CFLAGS=-m32
            make -s ARCH=i386
            echo 'export STATIC_LIBC=/tmp/musl-$MUSL_VERSION/lib/libc.a' >> $BASH_ENV
      - run:
          name: Build static goinsu x86
          command: |
            dub run reggae -- -b make -d ARCH=x86 -d BUILD_STATIC=true \
              -d STATIC_LIBC=$STATIC_LIBC --no_comp_db
            make
      - run:
          <<: *print_info
      - setup_remote_docker
      - run:
          <<: *install_docker
      - run: &test
          name: Test
          command: |
            sed -i "1s/glibc/musl/" .circleci/Dockerfile.test
            docker build -t test -f .circleci/Dockerfile.test .

workflows:
  version: 2
  build-and-test:
    jobs:
      - "x86_64"
      - "x86.static"
      - "x86_64.static"
