FROM busybox:glibc

RUN adduser testuser -D -h "" \
 && cat /etc/group | cut -d: -f1 | xargs -n1 addgroup testuser
 
COPY .ci/testsuite /bin/
COPY goinsu /bin/

RUN chmod +s /bin/goinsu

USER testuser
ENV HOME /opt/is/my/city

RUN id && testsuite
